### ISSUE TITLE
Incorrect display of results

### ISSUE THREAD

**Issue by PalFed** [flackr/crosswordle#20] opened 2022-02-09 21:17 UTC
<img width="1659" alt="Screenshot 2022-02-09 at 3 14 26 PM" src="https://user-images.githubusercontent.com/25444243/153291370-f8de4736-d4cc-47e8-8045-dd5713214d2c.png">

As seen in the screenshot above, the solution had only one 'n' in it, but the colors returned for attempts two and three suggest that the solution has two 'n's in it.

**Comment by flackr** [comment] 2022-02-10 04:30
This is a duplicate of #13. The last letter of the four letter word is the same yellow tile as the second letter of your 3 letter word. However, I could change the game so that the crossing tile counts as two separate guesses.

**Closed as completed by flackr** 2022-02-10 04:30 UTC
