### ISSUE TITLE
12/22/22 error

### ISSUE THREAD

**Issue by Hi777santa** [flackr/crosswordle#35] opened 2022-12-22 16:31 UTC
Answer isn’t acknowledging the second word as a viable word. No way to win

**Comment by flackr** [comment] 2022-12-22 17:28
Hi, thanks for the report. This is a duplicate of #32, but unfortunately it's hard to prevent browsers using the cached older file so I can't prevent people from running into this without a forced reload. Please reload the page and try entering it again.

**Closed as completed by flackr** 2022-12-22 17:28 UTC

**Comment by Hi777santa** [comment] 2022-12-22 22:30
Ah. Ok. I’m not able to see previous reports. But thanks for letting me know it’s an unfixable error. I look forward to these every day and will continue to do so. Thank you.
